name: Deploy Frontend MAGNO

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Install OpenConnect
      run: sudo apt-get install -y openconnect

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Connect to VPN
      run: |
        echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect --protocol=gp --user=${{ secrets.VPN_USER }} --passwd-on-stdin ${{ secrets.VPN_HOST }} -b
      env:
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        VPN_USER: ${{ secrets.VPN_USER }}
        VPN_HOST: ${{ secrets.VPN_HOST }}

    - name: Verify VPN connection
      run: ip a

    - name: List network routes
      run: ip route

    - name: Test internal connectivity with SSH
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} 'echo "SSH connection successful"'
        
    - name: Clone repository on remote server
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} '
          ls -a
          cd ~/magno/magno || exit;
          if [ ! -d ".git" ]; then
            git clone https://github.com/JackBlaze132/magno.git
          else
            cd magno
            git pull
          fi'

    - name: Build project on remote server
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} '
          cd ~/magno/magno/frontend;
          npm install;
          npm run build'
          
    - name: Restart PM2
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} "
        export PATH=\$PATH:/usr/local/nodejs/bin &&
        if pm2 list | grep -q 'Front_Magno'; then
          pm2 restart Front_Magno;
        else
          cd ~/magno/magno/frontend/dist &&
          pm2 start 'serve -s . -p 3000' --name Front_Magno;
        fi"


    - name: Post Checkout repository
      run: echo "Deployment complete"
